kind: pipeline
name: default


steps:

  - name: Deploy Test
    image: kontena/cli
    environment:
      KONTENA_URL:
        from_secret: kontena_url
      KONTENA_TOKEN:
        from_secret: kontena_token
      KONTENA_GRID: prod
      SSL_IGNORE_ERRORS: true
    commands:
      - echo "$KONTENA_URL"
      - kontena stack deploy together
  - name: docker
    image: plugins/docker
    settings:
      repo: corylogan/together
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Deploy To Kontena
    image: kontena/cli
    environment:
      KONTENA_URL:
        from_secret: kontena_url
      KONTENA_TOKEN:
        from_secret: kontena_token
      KONTENA_GRID: prod
      SSL_IGNORE_ERRORS: true
    commands:
      - kontena stack deploy together

branches:
  - master
