kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: corylogan/together
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Deploy To Kontena Production
    image: corylogan/kontena-cli
    envoronment:
      KONTENA_URL:
        from_secret: kontena_url
      KONTENA_TOKEN:
        from_secret: kontena_api_key

    commands:
      - SSL_IGNORE_ERRORS=true kontena stack deploy rails

branches:
  - master
